### ISSUE TITLE
how to generate se-ssd.wts file

### ISSUE THREAD

**Issue by chasingw** [jingyue202205/SE-SSD-AI-TRT#1]
hi, how to generate se-ssd.wts file

**Comment by jingyue202205** [comment]
> hi, how to generate se-ssd.wts file

SE-SSD-AI-TRT/tools/gen_wts.py for generate wts file.
firstly, You should configure the training environment，and ensure that the evaluation code can run. 
gen_wts.py are mainly based on tensorrtx(https://github.com/wang-xinyu/tensorrtx)
you can get more information from tensorrtx

**Comment by chasingw** [comment]
> > hi, how to generate se-ssd.wts file
> 
> SE-SSD-AI-TRT/tools/gen_wts.py for generate wts file. firstly, You should configure the training environment，and ensure that the evaluation code can run. gen_wts.py are mainly based on tensorrtx(https://github.com/wang-xinyu/tensorrtx) you can get more information from tensorrtx

got it, thanks for your help
